# 10: Tuning, a second implementation, stacking, and seed variance

Cost-sensitive *training* is a settled question (notebooks 04/06): it never
beat plain thresholding for the two strongest learners. This notebook asks a
different question given the same feature set (`no_origin_balance`) and the
same unweighted-plus-threshold recipe that already won, is there headroom left
in *how the model itself is built*? Four independent checks, each skippable on
its own:

1. **Hyperparameter search for XGBoost.** Every fit so far used one fixed
   hyperparameter set, chosen to match the comparison papers rather than tuned
   for this task.
2. **A second gradient-boosting implementation (LightGBM)**, at matched
   hyperparameters first, to separate "different implementation" from
   "tuning."
3. **Stacking** the four base learners through a logistic-regression
   meta-learner, on out-of-fold probabilities.
4. **Multi-seed variance** the report's own next-steps list already flags
   this as "the cheapest remaining credibility gain" (`report/RESULTS_SYNTHESIS.md`
   section 7): is NER 0.1314 a stable finding, or does it move with the seed?

**What is deliberately *not* attempted here: recalibration.**
`risk.optimal_threshold` already scans every possible cutpoint of the raw
score; Platt/isotonic calibration is a monotonic transform of that same score,
so it cannot change which rows get flagged at the NER-optimal cut only
relabel the threshold's numeric value. The one place it could matter is
putting differently-scaled base learners on comparable footing before
stacking, which section 3 handles directly rather than as a separate step.

Every result here writes to a new `results/10_*` file. Nothing under
`results/03_`-`08_` or `artifacts/` is touched promoting any winner found
here into the shipped model is a separate, later decision.

In [1]:
import json, sys, time
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.metrics import average_precision_score

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from momo_fraud import constants as C
from momo_fraud import data as D
from momo_fraud import evaluate as E
from momo_fraud import experiment as X
from momo_fraud import models as M
from momo_fraud import risk as RK
from momo_fraud import splits as S
from momo_fraud import viz
from momo_fraud.features import FeatureBuilder, columns_for

viz.apply_house_style()

# Resolves to the validation-selected decision when present, falling back to
# the original test-selected one. Both name the same rung; the preference
# order exists so a future re-derivation cannot silently fall back.
decision = X.load_experimental_rung()
RUNG = decision["experimental_rung"]
SEED = C.RANDOM_SEED
R = C.R_DEFAULT

baseline_row = (pd.read_csv(PROJECT_ROOT / "results" / "04_cost_sensitive.csv")
                .query("learner == 'xgboost' and split == 'test' and feature_set == @RUNG "
                       "and config == 'C'").iloc[0])
BASELINE_NER = float(baseline_row["ner"])
BASELINE_PR_AUC = float(baseline_row["pr_auc"])
print(f"rung: {RUNG}")
print(f"baseline to beat: XGBoost NER={BASELINE_NER:.4f}, PR-AUC={BASELINE_PR_AUC:.4f}")

rung: no_origin_balance
baseline to beat: XGBoost NER=0.1314, PR-AUC=0.8173

In [2]:
df = D.load()
y = df[C.TARGET].to_numpy()
split = S.stratified_split(y)

builder = FeatureBuilder().fit(df.iloc[split.train])
X_all = builder.transform(df)
cols = columns_for(RUNG, list(X_all.columns))

parts = {k: X_all.iloc[getattr(split, k)][cols] for k in ("train", "val", "test")}
labels = {k: y[getattr(split, k)] for k in ("train", "val", "test")}
X_train, X_val, X_test = parts["train"], parts["val"], parts["test"]
y_train, y_val, y_test = labels["train"], labels["val"], labels["test"]
print(f"{len(cols)} features at the '{RUNG}' rung, {len(X_train):,} train rows")

14 features at the 'no_origin_balance' rung, 4,453,834 train rows

## 1. Hyperparameter search for XGBoost

Full 5x5 repeated CV is not viable at this scale for a *search* it would be
25x the cost of the entire existing 28-fit grid, per candidate. Instead: a
bounded random search, one train/val fit per candidate with early stopping
against the existing validation split (reusing the same train/val boundary
every other fit in this study respects), ranked by validation PR-AUC. The
winner is then scored once, honestly, on the untouched test set.

In [ ]:
from xgboost import XGBClassifier

N_CANDIDATES = 8
# capped at the baselines own budget (300 estimators) rather than higher with
# early stopping: a low learning rate delays early stopping from ever
# triggering, which is what made an earlier uncapped version of this search
# run long enough to hit its own timeout. bounding the ceiling keeps every
# candidates worst case comparable to the fit times already measured in
# notebooks 03/04 (XGBoost ~123s at 300 estimators).
MAX_ESTIMATORS = 300
rng = np.random.default_rng(SEED)

def sample_candidate():
    return dict(
        max_depth=int(rng.integers(3, 9)),
        learning_rate=float(rng.choice([0.03, 0.05, 0.1, 0.2, 0.3])),
        subsample=float(rng.choice([0.6, 0.8, 1.0])),
        colsample_bytree=float(rng.choice([0.6, 0.8, 1.0])),
        min_child_weight=float(rng.choice([1, 3, 5, 10])),
        gamma=float(rng.choice([0.0, 0.1, 0.5, 1.0])),
    )

candidates = [sample_candidate() for _ in range(N_CANDIDATES)]
hpo_rows = []
hpo_path = PROJECT_ROOT / "results" / "10_xgboost_hpo_candidates.csv"

for i, params in enumerate(candidates):
    model = XGBClassifier(
        n_estimators=MAX_ESTIMATORS, tree_method="hist", eval_metric="aucpr",
        early_stopping_rounds=15, random_state=SEED, n_jobs=-1, **params,
    )
    start = time.perf_counter()
    model.fit(X_train, y_train, eval_set=[(X_val, y_val)], verbose=False)
    elapsed = time.perf_counter() - start

    val_scores = model.predict_proba(X_val)[:, 1]
    val_pr_auc = average_precision_score(y_val, val_scores)
    hpo_rows.append({
        "candidate": i, **params,
        "best_iteration": int(model.best_iteration), "val_pr_auc": val_pr_auc,
        "fit_seconds": elapsed,
    })
    print(f"[{i + 1}/{N_CANDIDATES}] val PR-AUC {val_pr_auc:.4f}  "
          f"({model.best_iteration} rounds, {elapsed:.0f}s)  {params}")

    # Persisted after every candidate, not just at the end: a slow later
    # candidate must not be able to erase the ones that already finished.
    pd.DataFrame(hpo_rows).to_csv(hpo_path, index=False)

hpo_df = pd.DataFrame(hpo_rows).sort_values("val_pr_auc", ascending=False)
hpo_df.round(4)

[1/8] val PR-AUC 0.8115  (221 rounds, 167s)  {'max_depth': 3, 'learning_rate': 0.2, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3.0, 'gamma': 1.0}

[2/8] val PR-AUC 0.8232  (299 rounds, 206s)  {'max_depth': 3, 'learning_rate': 0.2, 'subsample': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5.0, 'gamma': 1.0}

[3/8] val PR-AUC 0.8401  (233 rounds, 171s)  {'max_depth': 7, 'learning_rate': 0.2, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'gamma': 0.0}

[4/8] val PR-AUC 0.8490  (126 rounds, 119s)  {'max_depth': 8, 'learning_rate': 0.1, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'gamma': 1.0}

[5/8] val PR-AUC 0.8411  (97 rounds, 94s)  {'max_depth': 7, 'learning_rate': 0.2, 'subsample': 0.8, 'colsample_bytree': 1.0, 'min_child_weight': 5.0, 'gamma': 0.1}

[6/8] val PR-AUC 0.8386  (299 rounds, 246s)  {'max_depth': 5, 'learning_rate': 0.05, 'subsample': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 10.0, 'gamma': 0.0}

[7/8] val PR-AUC 0.8199  (107 rounds, 128s)  {'max_depth': 8, 'learning_rate': 0.3, 'subsample': 0.6, 'colsample_bytree': 0.8, 'min_child_weight': 1.0, 'gamma': 1.0}

[8/8] val PR-AUC 0.8472  (298 rounds, 279s)  {'max_depth': 7, 'learning_rate': 0.05, 'subsample': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 3.0, 'gamma': 1.0}

,candidate,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,best_iteration,val_pr_auc,fit_seconds
3,3,8,0.10,0.8,0.8,1.0,1.0,126,0.8490,119.3726
7,7,7,0.05,0.6,1.0,3.0,1.0,298,0.8472,278.5507
4,4,7,0.20,0.8,1.0,5.0,0.1,97,0.8411,93.5393
2,2,7,0.20,1.0,1.0,5.0,0.0,233,0.8401,171.2583
5,5,5,0.05,0.6,0.8,10.0,0.0,299,0.8386,245.7329
1,1,3,0.20,0.6,0.6,5.0,1.0,299,0.8232,206.4676
6,6,8,0.30,0.6,0.8,1.0,1.0,107,0.8199,127.8084
0,0,3,0.20,0.8,0.8,3.0,1.0,221,0.8115,167.1187

In [4]:
winner_params = {k: hpo_df.iloc[0][k] for k in
                ["max_depth", "learning_rate", "subsample", "colsample_bytree",
                 "min_child_weight", "gamma"]}
winner_params["max_depth"] = int(winner_params["max_depth"])
winner_n_estimators = int(hpo_df.iloc[0]["best_iteration"]) or 1
print("winning candidate:", winner_params, "at", winner_n_estimators, "rounds")

start = time.perf_counter()
tuned_model = XGBClassifier(
    n_estimators=winner_n_estimators, tree_method="hist", eval_metric="aucpr",
    random_state=SEED, n_jobs=-1, **winner_params,
)
tuned_model.fit(X_train, y_train)
tuned_fit_seconds = time.perf_counter() - start

tuned_val_scores = tuned_model.predict_proba(X_val)[:, 1].astype("float32")
tuned_test_scores = tuned_model.predict_proba(X_test)[:, 1].astype("float32")

E.save_predictions(y_val, tuned_val_scores, learner="xgboost_tuned", config="C",
                   split="val", seed=SEED, tag=RUNG)
E.save_predictions(y_test, tuned_test_scores, learner="xgboost_tuned", config="C",
                   split="test", seed=SEED, tag=RUNG)

chosen = E.select_threshold(y_val, tuned_val_scores, "ner_optimal", R)
tuned_row = E.full_report(
    y_test, tuned_test_scores, threshold=chosen.threshold, r=R,
    learner="xgboost_tuned", config="C", variant="tuned", level="none",
    threshold_rule="ner_optimal", split="test", seed=SEED, feature_set=RUNG,
    fit_seconds=tuned_fit_seconds, n_train=len(y_train),
)
json.dumps({"winner_params": winner_params, "n_estimators": winner_n_estimators,
           "test_ner": tuned_row["ner"], "test_pr_auc": tuned_row["pr_auc"]}, indent=2)

winning candidate: {'max_depth': 8, 'learning_rate': np.float64(0.1), 'subsample': np.float64(0.8), 'colsample_bytree': np.float64(0.8), 'min_child_weight': np.float64(1.0), 'gamma': np.float64(1.0)} at 126 rounds

'{\n  "winner_params": {\n    "max_depth": 8,\n    "learning_rate": 0.1,\n    "subsample": 0.8,\n    "colsample_bytree": 0.8,\n    "min_child_weight": 1.0,\n    "gamma": 1.0\n  },\n  "n_estimators": 126,\n  "test_ner": 0.12385685954522706,\n  "test_pr_auc": 0.815250778311826\n}'

In [5]:
E.save_json({"winner_params": winner_params, "n_estimators": winner_n_estimators,
            "val_pr_auc": float(hpo_df.iloc[0]["val_pr_auc"]),
            "test_ner": tuned_row["ner"], "test_pr_auc": tuned_row["pr_auc"],
            "baseline_ner": BASELINE_NER, "baseline_pr_auc": BASELINE_PR_AUC},
           "10_xgboost_hpo_winner")

print(f"tuned  : NER {tuned_row['ner']:.4f}, PR-AUC {tuned_row['pr_auc']:.4f}")
print(f"baseline: NER {BASELINE_NER:.4f}, PR-AUC {BASELINE_PR_AUC:.4f}")
print(f"NER change: {(tuned_row['ner'] - BASELINE_NER) / BASELINE_NER * 100:+.1f}%")

tuned  : NER 0.1239, PR-AUC 0.8153
baseline: NER 0.1314, PR-AUC 0.8173
NER change: -5.7%

## 2. A second gradient-boosting implementation: LightGBM

Same hyperparameter *budget* as the untuned XGBoost baseline (depth 6, 300
estimators, lr 0.1, subsample/colsample 0.8) this isolates "different
implementation" from "tuning." `make_learner_extended` in `models.py` adds
this without touching the four existing `make_learner` branches.

In [6]:
start = time.perf_counter()
lgbm_model = M.make_learner_extended("lightgbm", seed=SEED)
lgbm_model.fit(X_train, y_train)
lgbm_fit_seconds = time.perf_counter() - start

lgbm_val_scores = lgbm_model.predict_proba(X_val)[:, 1].astype("float32")
lgbm_test_scores = lgbm_model.predict_proba(X_test)[:, 1].astype("float32")

E.save_predictions(y_val, lgbm_val_scores, learner="lightgbm", config="C",
                   split="val", seed=SEED, tag=RUNG)
E.save_predictions(y_test, lgbm_test_scores, learner="lightgbm", config="C",
                   split="test", seed=SEED, tag=RUNG)

chosen = E.select_threshold(y_val, lgbm_val_scores, "ner_optimal", R)
lgbm_row = E.full_report(
    y_test, lgbm_test_scores, threshold=chosen.threshold, r=R,
    learner="lightgbm", config="C", variant="unweighted", level="none",
    threshold_rule="ner_optimal", split="test", seed=SEED, feature_set=RUNG,
    fit_seconds=lgbm_fit_seconds, n_train=len(y_train),
)

learner_comparison = pd.DataFrame([
    {"learner": "xgboost (baseline)", "ner": BASELINE_NER, "pr_auc": BASELINE_PR_AUC},
    {"learner": "xgboost (tuned)", "ner": tuned_row["ner"], "pr_auc": tuned_row["pr_auc"]},
    {"learner": "lightgbm (matched budget)", "ner": lgbm_row["ner"], "pr_auc": lgbm_row["pr_auc"]},
])
E.save_results(learner_comparison.to_dict("records"), "10_learner_comparison")
print("legit-class max predicted probability (test):",
     f"{lgbm_test_scores[y_test == 0].max():.4f}")
learner_comparison.round(4)

legit-class max predicted probability (test): 1.0000

                     learner     ner  pr_auc
0         xgboost (baseline)  0.1314  0.8173
1            xgboost (tuned)  0.1239  0.8153
2  lightgbm (matched budget)  0.7905  0.0433

**LightGBM loses badly here, and that is a finding worth stating rather than
tuning away.** At a matched hyperparameter budget its test PR-AUC lands far
below XGBoost's, and some legitimate transactions get predicted probability
1.0 a sign of leaf-wise overfitting: LightGBM's leaf-wise growth (best-gain
splits, unconstrained by depth the way XGBoost's default depth-wise growth
is) will chase a few high-gain splits on a severely imbalanced problem
(0.129% prevalence) into leaves confident enough to assign near-certainty to
examples that do not deserve it. `subsample_freq=1` was added to
`make_learner_extended` because LightGBM otherwise silently ignores
`subsample` entirely (a real API difference from XGBoost, not a research
finding) that fix alone was not enough to close the gap. Chasing further
regularization here would cross from "same budget, different implementation"
into "tuned until it wins," which is exactly the kind of post-hoc search this
study elsewhere `04_cost_sensitive.ipynb`, the benchmark check in
`03_baselines.ipynb` is built to guard against. The honest conclusion: a fair
LightGBM comparison needs its own dedicated tuning pass, which is out of
scope here, and it is excluded from the "did anything beat baseline" verdict
below for that reason.

## 3. Stacking

A logistic-regression meta-learner on out-of-fold probabilities from the four
existing base learners. 3-fold (not repeated, not 5-fold) to keep this
affordable: one-shot out-of-fold generation only needs enough folds that no
row scores itself, not a variance study. Val/test meta-features reuse the
*already-cached* `unweighted` predictions from notebooks 03/04
(`E.load_predictions(..., tag=RUNG)`) rather than refitting the base learners
a second time.

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold

N_FOLDS = 3
skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)

oof = {name: np.zeros(len(y_train), dtype="float32") for name in C.LEARNERS}

for name in C.LEARNERS:
    start = time.perf_counter()
    for fold_train_idx, fold_oof_idx in skf.split(X_train, y_train):
        fold_model = M.make_learner(name, seed=SEED)
        fold_model.fit(X_train.iloc[fold_train_idx], y_train[fold_train_idx])
        oof[name][fold_oof_idx] = fold_model.predict_proba(
            X_train.iloc[fold_oof_idx])[:, 1]
    print(f"{name}: {N_FOLDS}-fold OOF in {time.perf_counter() - start:.0f}s")

meta_X_train = np.column_stack([oof[name] for name in C.LEARNERS])

logistic_regression: 3-fold OOF in 45s

decision_tree: 3-fold OOF in 176s

random_forest: 3-fold OOF in 539s

xgboost: 3-fold OOF in 438s

In [8]:
val_probs, test_probs = {}, {}
for name in C.LEARNERS:
    val_probs[name] = E.load_predictions(name, "unweighted", "val", SEED, tag=RUNG)["score"].to_numpy()
    test_probs[name] = E.load_predictions(name, "unweighted", "test", SEED, tag=RUNG)["score"].to_numpy()

meta_X_val = np.column_stack([val_probs[name] for name in C.LEARNERS])
meta_X_test = np.column_stack([test_probs[name] for name in C.LEARNERS])

meta = LogisticRegression(max_iter=1000, random_state=SEED)
meta.fit(meta_X_train, y_train)

stack_val_scores = meta.predict_proba(meta_X_val)[:, 1].astype("float32")
stack_test_scores = meta.predict_proba(meta_X_test)[:, 1].astype("float32")

E.save_predictions(y_val, stack_val_scores, learner="stack_lr", config="C",
                   split="val", seed=SEED, tag=RUNG)
E.save_predictions(y_test, stack_test_scores, learner="stack_lr", config="C",
                   split="test", seed=SEED, tag=RUNG)

chosen = E.select_threshold(y_val, stack_val_scores, "ner_optimal", R)
stack_row = E.full_report(
    y_test, stack_test_scores, threshold=chosen.threshold, r=R,
    learner="stack_lr", config="C", variant="stacked", level="none",
    threshold_rule="ner_optimal", split="test", seed=SEED, feature_set=RUNG,
    fit_seconds=np.nan, n_train=len(y_train),
)

stacking_results = pd.DataFrame([
    {"learner": "xgboost (baseline)", "ner": BASELINE_NER, "pr_auc": BASELINE_PR_AUC},
    {"learner": "stack (LR meta on 4 base learners)", "ner": stack_row["ner"],
    "pr_auc": stack_row["pr_auc"]},
])
E.save_results(stacking_results.to_dict("records"), "10_stacking_results")
print("meta-learner coefficients:", dict(zip(C.LEARNERS, meta.coef_[0].round(3))))
stacking_results.round(4)

meta-learner coefficients: {'logistic_regression': np.float64(1.716), 'decision_tree': np.float64(3.778), 'random_forest': np.float64(4.315), 'xgboost': np.float64(6.168)}

                              learner     ner  pr_auc
0                  xgboost (baseline)  0.1314  0.8173
1  stack (LR meta on 4 base learners)  0.1206  0.8105

## 4. Multi-seed variance

`report/RESULTS_SYNTHESIS.md` section 6.8 already flags that the H1
separated/overlapping count moved between runs from XGBoost's own
non-deterministic parallel reduction evidence that seed variance isn't
negligible. This re-runs the unweighted grid (configs A/B/C) at three
additional seeds and combines them with the existing seed-42 result to ask:
is NER 0.1314 a stable number, or does it move?

In [9]:
EXTRA_SEEDS = [7, 13, 99]

start = time.perf_counter()
multiseed_new = X.run_grid(
    parts["train"], labels["train"], parts["val"], labels["val"],
    parts["test"], labels["test"],
    variants=["unweighted"], seeds=EXTRA_SEEDS, r=R, feature_set=RUNG,
)
print(f"multi-seed grid: {time.perf_counter() - start:.0f}s")

seed42_baseline = (pd.read_csv(PROJECT_ROOT / "results" / "04_cost_sensitive.csv")
                   .query("split == 'test' and feature_set == @RUNG and config == 'C'")
                   .assign(seed=C.RANDOM_SEED))

all_seeds = pd.concat([
    seed42_baseline, multiseed_new.query("split == 'test' and config == 'C'")
], ignore_index=True)

variance = (all_seeds.groupby("learner")
           .agg(mean_ner=("ner", "mean"), std_ner=("ner", "std"),
                mean_pr_auc=("pr_auc", "mean"), std_pr_auc=("pr_auc", "std"),
                n_seeds=("seed", "nunique"))
           .reset_index())
E.save_results(variance.to_dict("records"), "10_multiseed_ner")
variance.round(4)

[1/12] logistic_regression / unweighted / seed 7 …

   13.1s  test PR-AUC 0.5040

[2/12] decision_tree / unweighted / seed 7 …

   92.9s  test PR-AUC 0.7298

[3/12] random_forest / unweighted / seed 7 …

  206.7s  test PR-AUC 0.7946

[4/12] xgboost / unweighted / seed 7 …

  142.6s  test PR-AUC 0.8134

[5/12] logistic_regression / unweighted / seed 13 …

   11.5s  test PR-AUC 0.5040

[6/12] decision_tree / unweighted / seed 13 …

   83.6s  test PR-AUC 0.7298

[7/12] random_forest / unweighted / seed 13 …

  167.8s  test PR-AUC 0.7961

[8/12] xgboost / unweighted / seed 13 …

  237.5s  test PR-AUC 0.8171

[9/12] logistic_regression / unweighted / seed 99 …

   13.9s  test PR-AUC 0.5040

[10/12] decision_tree / unweighted / seed 99 …

   83.4s  test PR-AUC 0.7297

[11/12] random_forest / unweighted / seed 99 …

  212.3s  test PR-AUC 0.7978

[12/12] xgboost / unweighted / seed 99 …

  174.7s  test PR-AUC 0.8122

multi-seed grid: 1679s

               learner  mean_ner  std_ner  mean_pr_auc  std_pr_auc  n_seeds
0        decision_tree    0.1527   0.0000       0.7298      0.0000        4
1  logistic_regression    0.2499   0.0000       0.5040      0.0000        4
2        random_forest    0.1248   0.0053       0.7963      0.0013        4
3              xgboost    0.1315   0.0043       0.8150      0.0026        4

## Summary: did anything here beat 0.1314?

LightGBM is included in the table for the record but excluded from the
verdict column section 2 established that its matched-budget result
reflects under-regularized leaf-wise overfitting, not a genuine
implementation comparison, so treating its loss (or a tuned-until-it-wins
future version of it) as evidence either way would overstate what a single,
undertuned fit can tell us.

In [ ]:
summary = pd.DataFrame([
    {"approach": "shipped baseline (XGBoost, config C)", "ner": BASELINE_NER, "pr_auc": BASELINE_PR_AUC},
    {"approach": "XGBoost, tuned hyperparameters", "ner": tuned_row["ner"], "pr_auc": tuned_row["pr_auc"]},
    {"approach": "LightGBM, matched budget (not a fair comparison see section 2)",
    "ner": lgbm_row["ner"], "pr_auc": lgbm_row["pr_auc"]},
    {"approach": "Stack (LR meta on 4 base learners)", "ner": stack_row["ner"], "pr_auc": stack_row["pr_auc"]},
]).sort_values("ner")
summary["beats_baseline"] = (summary["ner"] < BASELINE_NER).astype(object)
summary.loc[summary["approach"].str.startswith("LightGBM"), "beats_baseline"] = np.nan
E.save_results(summary.to_dict("records"), "10_summary")
summary.round(4)

,approach,ner,pr_auc,beats_baseline
3,Stack (LR meta on 4 base learners),0.1206,0.8105,True
1,"XGBoost, tuned hyperparameters",0.1239,0.8153,True
0,"shipped baseline (XGBoost, config C)",0.1314,0.8173,False
2,"LightGBM, matched budget (not a fair compariso...",0.7905,0.0433,NaN